#!/usr/bin/env bash

sudo pacman -S i3-wm i3status

pacman_packages=(
    "polkit"
    "tmux"
    "stow"
    "picom"
    "arandr"
    "exfat-utils"
    "ntfs-3g"
    "maim"
    "unclutter"
    "unzip"
    "xcape"
    "xclip"
    "yt-dlp"
    "zathura"
    "zathura-pdf-mupdf"
    "poppler"
    "fzf"
    # "gparted"
    "ueberzug"
    "mediainfo"
    "bat"
    "ffmpeg"
    "ffmpegthumbnailer"
    "odt2txt"
    "atool"
    "mpd"
    "mpv"
    "mpc"
    "ncmpcpp"
    "dunst"
    "libnotify"
    # "libreoffice"
    "moreutils"
    "findutils"
    "gawk"
    "ripgrep"
    # "gimp"
    "highlight"
    "less"
    "lua"
    "pinentry"
    "sed"
    "unrar"
    "zip"
    "unzip"
    "tzdata"
    "whois"
    "xwallpaper"
    "ninja"
    "direnv"
    "nodejs"
    "npm"
    "wmname"
    "go"
    # "csvlens"

    #"chromium"

    "gtk2"
    "gtk3"
    # "gtk4"
    "lxappearance"
    "qt5ct"
    "python-qdarkstyle"

    # "ttf-linux-libertine"
    # "ttf-font-awesome"
    # "ttf-dejavu"
    "ttc-iosevka"
    #"noto-fonts"
    #"noto-fonts-emoji"

    "python"
    "python-pip"

    "lazygit"
    "btop"
    "keepassxc"
    "fd"
    #"ttf-jetbrains-mono"
    #"ttf-hack-nerd"
    "dust"
    "github-cli"
    "xdotool"

#"networkmanager-vpnc"
#"vpnc"
)

sudo pacman -S ${pacman_packages[*]} || exit 1

paru_packages=(
    "lf-bin"
    "zsh-fast-syntax-highlighting"
    "zsh-system-clipboard-git"
    # "simple-mtpfs"
    "htop-vim"
    # "task-spooler"
    # "abook"
    "nsxiv"
    "mmv-go"

    # "burpsuite"
    # "postman-bin"
    "brave-bin"
    "obsidian-bin"
    # "noto-color-emoji-fontconfig"
)

for paru_package in "${paru_packages[@]}"; do
    # paru -S "$paru_package" --noconfirm
    paru -S "$paru_package"
done

echo -e "\nSuccess"
